// flow-typed signature: 0c75089ef0e916c841d04c5c9bc25eff
// flow-typed version: <<STUB>>/brotli-webpack-plugin_v^0.5.0/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'brotli-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'brotli-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'brotli-webpack-plugin/compress' {
  declare module.exports: any;
}

declare module 'brotli-webpack-plugin/test/fixtures/entry' {
  declare module.exports: any;
}

declare module 'brotli-webpack-plugin/test/index.test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'brotli-webpack-plugin/compress.js' {
  declare module.exports: $Exports<'brotli-webpack-plugin/compress'>;
}
declare module 'brotli-webpack-plugin/index' {
  declare module.exports: $Exports<'brotli-webpack-plugin'>;
}
declare module 'brotli-webpack-plugin/index.js' {
  declare module.exports: $Exports<'brotli-webpack-plugin'>;
}
declare module 'brotli-webpack-plugin/test/fixtures/entry.js' {
  declare module.exports: $Exports<'brotli-webpack-plugin/test/fixtures/entry'>;
}
declare module 'brotli-webpack-plugin/test/index.test.js' {
  declare module.exports: $Exports<'brotli-webpack-plugin/test/index.test'>;
}
