// flow-typed signature: 5c2a1c7fe707f8a48f3f14d1ff197543
// flow-typed version: <<STUB>>/browserslist_v^2.11.0/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'browserslist'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'browserslist' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'browserslist/cli' {
  declare module.exports: any;
}

// Filename aliases
declare module 'browserslist/cli.js' {
  declare module.exports: $Exports<'browserslist/cli'>;
}
declare module 'browserslist/index' {
  declare module.exports: $Exports<'browserslist'>;
}
declare module 'browserslist/index.js' {
  declare module.exports: $Exports<'browserslist'>;
}
