// flow-typed signature: 8e69058f85f28eb1a72880024b467cbe
// flow-typed version: <<STUB>>/nskeymirror_v^0.1.2/flow_v0.66.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'nskeymirror'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'nskeymirror' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'nskeymirror/__tests__/nskeymirror-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'nskeymirror/__tests__/nskeymirror-test.js' {
  declare module.exports: $Exports<'nskeymirror/__tests__/nskeymirror-test'>;
}
declare module 'nskeymirror/index' {
  declare module.exports: $Exports<'nskeymirror'>;
}
declare module 'nskeymirror/index.js' {
  declare module.exports: $Exports<'nskeymirror'>;
}
