// flow-typed signature: 10d872e325bbe810a34a9c5372612582
// flow-typed version: <<STUB>>/postcss-sass_v^0.2.0/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'postcss-sass'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'postcss-sass' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'postcss-sass/stringifier' {
  declare module.exports: any;
}

declare module 'postcss-sass/stringify' {
  declare module.exports: any;
}

// Filename aliases
declare module 'postcss-sass/index' {
  declare module.exports: $Exports<'postcss-sass'>;
}
declare module 'postcss-sass/index.js' {
  declare module.exports: $Exports<'postcss-sass'>;
}
declare module 'postcss-sass/stringifier.js' {
  declare module.exports: $Exports<'postcss-sass/stringifier'>;
}
declare module 'postcss-sass/stringify.js' {
  declare module.exports: $Exports<'postcss-sass/stringify'>;
}
