// flow-typed signature: 71a1ce9a898d35cbfc48bdb31b475ff2
// flow-typed version: <<STUB>>/routes_v^2.1.0/flow_v0.63.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'routes'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'routes' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'routes/dist/routes' {
  declare module.exports: any;
}

declare module 'routes/test/example' {
  declare module.exports: any;
}

declare module 'routes/test/next' {
  declare module.exports: any;
}

declare module 'routes/test/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'routes/dist/routes.js' {
  declare module.exports: $Exports<'routes/dist/routes'>;
}
declare module 'routes/index' {
  declare module.exports: $Exports<'routes'>;
}
declare module 'routes/index.js' {
  declare module.exports: $Exports<'routes'>;
}
declare module 'routes/test/example.js' {
  declare module.exports: $Exports<'routes/test/example'>;
}
declare module 'routes/test/next.js' {
  declare module.exports: $Exports<'routes/test/next'>;
}
declare module 'routes/test/test.js' {
  declare module.exports: $Exports<'routes/test/test'>;
}
