// flow-typed signature: cab2dffdac40cd192804594b017a0a99
// flow-typed version: <<STUB>>/stylelint-no-unsupported-browser-features_v^1.0.1/flow_v0.62.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'stylelint-no-unsupported-browser-features'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'stylelint-no-unsupported-browser-features' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'stylelint-no-unsupported-browser-features/lib/cleanWarningText' {
  declare module.exports: any;
}

declare module 'stylelint-no-unsupported-browser-features/lib/parseOptions' {
  declare module.exports: any;
}

// Filename aliases
declare module 'stylelint-no-unsupported-browser-features/index' {
  declare module.exports: $Exports<'stylelint-no-unsupported-browser-features'>;
}
declare module 'stylelint-no-unsupported-browser-features/index.js' {
  declare module.exports: $Exports<'stylelint-no-unsupported-browser-features'>;
}
declare module 'stylelint-no-unsupported-browser-features/lib/cleanWarningText.js' {
  declare module.exports: $Exports<'stylelint-no-unsupported-browser-features/lib/cleanWarningText'>;
}
declare module 'stylelint-no-unsupported-browser-features/lib/parseOptions.js' {
  declare module.exports: $Exports<'stylelint-no-unsupported-browser-features/lib/parseOptions'>;
}
